In [1]:
import numpy as np
import pandas as pd
data1= pd.read_csv("C:\\Users\\SAGEABLE\\Desktop\\case study\\data1.csv")
data2=pd.read_csv("C:\\Users\\SAGEABLE\\Desktop\\case study\\data2.csv")

In [9]:
#1.	Create a table from Data 1 where MPI of Urban and Rural are greater than Itâ€™s Average
print 'average of MPI urban', np.mean(data1["MPI Urban"])
print 'average of MPI rural',np.mean(data1["MPI Rural"])
new_table =data1[(data1["MPI Rural"] > np.mean(data1["MPI Rural"])) & (data1["MPI Urban"] > np.mean(data1["MPI Urban"]))]
print new_table
#new_table.to_csv("C:\\Users\\SAGEABLE\\Desktop\\case study\\1table.csv")  # to output in csv file

average of MPI urban 0.0807171717172
average of MPI rural 0.216603960396
     ISO                            Country  MPI Urban  Headcount Ratio Urban  \
63   TGO                               Togo      0.081                   19.6
65   PAK                           Pakistan      0.087                   20.0
66   NAM                            Namibia      0.087                   20.3
67   CMR                           Cameroon      0.091                   19.9
68   MWI                             Malawi      0.098                   23.2
69   BGD                         Bangladesh      0.100                   22.5
70   COG                 Congo, Republic of      0.105                   24.5
71   RWA                             Rwanda      0.110                   24.8
72   HTI                              Haiti      0.112                   25.2
73   MDG                         Madagascar      0.113                   24.9
74   MRT                         Mauritania      0.119                   25.2
75   TZA       Tanzania, United Republic of      0.122                   27.7
76   DJI                           Djibouti      0.127                   27.2
77   ZMB                             Zambia      0.130                   29.5
78   NGA                            Nigeria      0.132                   28.1
79   AFG                        Afghanistan      0.132                   28.8
80   UGA                             Uganda      0.133                   29.2
81   SDN                              Sudan      0.133                   28.7
82   SEN                            Senegal      0.142                   29.7
83   CIV                      Cote d'Ivoire      0.164                   35.0
84   GIN                             Guinea      0.176                   37.7
85   TLS                        Timor-Leste      0.176                   37.3
86   GMB                             Gambia      0.183                   38.3
87   MLI                               Mali      0.189                   40.9
88   MOZ                         Mozambique      0.189                   38.2
89   BEN                              Benin      0.192                   41.0
90   GNB                      Guinea-Bissau      0.199                   43.6
91   BDI                            Burundi      0.209                   43.1
92   BFA                       Burkina Faso      0.226                   45.8
93   COD  Congo, Democratic Republic of the      0.228                   48.6
94   ETH                           Ethiopia      0.230                   46.4
95   SLE                       Sierra Leone      0.271                   56.3
96   NER                              Niger      0.276                   53.9
97   CAF           Central African Republic      0.289                   58.2
98   LBR                            Liberia      0.290                   60.5
99   SOM                            Somalia      0.293                   55.9
100  TCD                               Chad      0.351                   64.8
101  SSD                        South Sudan      0.459                   82.5

     Intensity of Deprivation Urban  MPI Rural  Headcount Ratio Rural  \
63                             41.5      0.356                  68.55
65                             43.3      0.299                  55.70
66                             43.0      0.288                  61.46
67                             45.6      0.393                  70.18
68                             42.4      0.277                  58.90
69                             44.7      0.231                  48.21
70                             42.8      0.316                  66.45
71                             44.2      0.289                  59.78
72                             44.6      0.341                  65.90
73                             45.3      0.396                  73.70
74                             47.0      0.413                  72.92
75                             44.3      0.351                  68.56
76                             46.6      0.440                  83.18
77                             44.0      0.380                  74.20
78                             47.0      0.416                  69.98
79                             45.8      0.347                  64.66
80                             45.5      0.408                  77.07
81                             46.3      0.356                  64.50
82                             47.7      0.472                  81.04
83                             46.8      0.429                  78.04
84                             46.6      0.591                  92.61
85                             47.3      0.414                  77.03
86                             47.8      0.459                  81.97
87                             46.3      0.530                  87.73
88                             49.6      0.480                  83.90
89                             46.8      0.386                  76.90
90                             45.7      0.507                  85.36
91                             48.5      0.481                  84.91
92                             49.4      0.621                  94.66
93                             47.0      0.486                  88.18
94                             49.5      0.637                  96.27
95                             48.2      0.551                  92.03
96                             51.2      0.669                  96.19
97                             49.7      0.519                  89.79
98                             48.0      0.481                  84.86
99                             52.4      0.651                  96.92
100                            54.1      0.609                  93.41
101                            55.7      0.591                  94.00

     Intensity of Deprivation Rural
63                             51.9
65                             53.6
66                             46.9
67                             56.0
68                             47.0
69                             47.9
70                             47.5
71                             48.4
72                             51.7
73                             53.8
74                             56.6
75                             51.2
76                             52.9
77                             51.3
78                             59.5
79                             53.6
80                             52.9
81                             55.1
82                             58.3
83                             55.0
84                             63.9
85                             53.7
86                             56.0
87                             60.5
88                             57.2
89                             50.2
90                             59.4
91                             56.6
92                             65.6
93                             55.1
94                             66.2
95                             59.8
96                             69.5
97                             57.8
98                             56.6
99                             67.2
100                            65.2
101                            62.8

In [44]:
#2.	Get the Count of Rows where any of the line Items is not having the Value (from Data1 and Data2)
total=0
for i in range(len(data1.isnull().sum())):
    total= data1.isnull().sum()[i]+total
print "Number of rows: {} not having the value in any of line items in data1".format(total)
print data1.isnull().sum()    # 5 rows having NAN
total=0
for i in range(len(data2.isnull().sum())):
    total= data2.isnull().sum()[i]+total
print "Number of rows: {} not having the value in any of line items in data2".format(total)
print data2.isnull().sum()    # 1 row having NAN

Number of rows: 5 not having the value in any of line items in data1
ISO                               0
Country                           0
MPI Urban                         3
Headcount Ratio Urban             0
Intensity of Deprivation Urban    1
MPI Rural                         1
Headcount Ratio Rural             0
Intensity of Deprivation Rural    0
first name                        0
dtype: int64
Number of rows: 1 not having the value in any of line items in data2
ISO country code                     0
Country                              0
Sub-national region                  0
World region                         0
MPI National                         0
MPI Regional                         0
Headcount Ratio Regional             0
Intensity of deprivation Regional    1
dtype: int64

In [10]:
#3.	Create a new column as first name to get the first name of the Country (from Data 1)
from pycountry import countries
from iso3166 import countries
first_name=[]
for i in data1.ISO:
    first_name.append(countries.get(i).apolitical_name.split()[0])
first_name=pd.DataFrame({'first name':first_name})
data1=data1.join(first_name)
print data1
#data1.to_csv("C:\\Users\\SAGEABLE\\Desktop\\case study\\3table.csv")  # to output in csv file

     ISO                                     Country  MPI Urban  \
0    KAZ                                  Kazakhstan      0.000
1    SRB                                      Serbia        NaN
2    KGZ                                  Kyrgyzstan        NaN
3    TUN                                     Tunisia        NaN
4    ARM                                     Armenia      0.001
5    MKD  Macedonia, The former Yugoslav Republic of      0.001
6    TKM                                Turkmenistan      0.001
7    MDA                        Moldova, Republic of      0.001
8    GUY                                      Guyana      0.001
9    MNE                                  Montenegro      0.002
10   LCA                                 Saint Lucia      0.002
11   MEX                                      Mexico      0.002
12   THA                                    Thailand      0.002
13   BIH                      Bosnia and Herzegovina      0.002
14   DZA                                     Algeria      0.003
15   ALB                                     Albania      0.003
16   UKR                                     Ukraine      0.003
17   BRB                                    Barbados      0.004
18   UZB                                  Uzbekistan      0.004
19   PSE                        Palestine, State ofa      0.004
20   JAM                                     Jamaica      0.004
21   ECU                                     Ecuador      0.005
22   MDV                                    Maldives      0.005
23   JOR                                      Jordan      0.006
24   BLZ                                      Belize      0.006
25   CHN                                       China      0.007
26   EGY                                       Egypt      0.008
27   SUR                                    Suriname      0.008
28   COL                                    Colombia      0.009
29   MAR                                     Morocco      0.009
..   ...                                         ...        ...
72   HTI                                       Haiti      0.112
73   MDG                                  Madagascar      0.113
74   MRT                                  Mauritania      0.119
75   TZA                Tanzania, United Republic of      0.122
76   DJI                                    Djibouti      0.127
77   ZMB                                      Zambia      0.130
78   NGA                                     Nigeria      0.132
79   AFG                                 Afghanistan      0.132
80   UGA                                      Uganda      0.133
81   SDN                                       Sudan      0.133
82   SEN                                     Senegal      0.142
83   CIV                               Cote d'Ivoire      0.164
84   GIN                                      Guinea      0.176
85   TLS                                 Timor-Leste      0.176
86   GMB                                      Gambia      0.183
87   MLI                                        Mali      0.189
88   MOZ                                  Mozambique      0.189
89   BEN                                       Benin      0.192
90   GNB                               Guinea-Bissau      0.199
91   BDI                                     Burundi      0.209
92   BFA                                Burkina Faso      0.226
93   COD           Congo, Democratic Republic of the      0.228
94   ETH                                    Ethiopia      0.230
95   SLE                                Sierra Leone      0.271
96   NER                                       Niger      0.276
97   CAF                    Central African Republic      0.289
98   LBR                                     Liberia      0.290
99   SOM                                     Somalia      0.293
100  TCD                                        Chad      0.351
101  SSD                                 South Sudan      0.459

     Headcount Ratio Urban  Intensity of Deprivation Urban  MPI Rural  \
0                      0.0                            33.3      0.000
1                      0.1                            41.4      0.002
2                      0.1                            40.2      0.003
3                      0.1                            35.6      0.012
4                      0.2                            33.3      0.001
5                      0.3                            36.3      0.004
6                      0.4                            33.9      0.001
7                      0.3                            42.2      0.003
8                      0.4                            38.2      0.017
9                      0.4                            47.2      0.000
10                     0.5                            36.7      0.004
11                     0.5                            38.0      0.014
12                     0.6                            37.1      0.004
13                     0.6                             NaN      0.002
14                     0.7                            36.9      0.011
15                     0.8                            37.7      0.007
16                     1.0                            33.7      0.006
17                     1.1                            34.2      0.002
18                     1.1                            33.9      0.010
19                     1.1                            38.5      0.003
20                     1.1                            40.0      0.010
21                     1.5                            36.5      0.030
22                     1.6                            33.3      0.024
23                     1.7                            34.7      0.007
24                     1.6                            37.9      0.028
25                     1.9                            38.9      0.028
26                     2.1                            36.8      0.017
27                     2.3                            36.7      0.063
28                     2.3                            37.2      0.061
29                     2.4                            36.2      0.139
..                     ...                             ...        ...
72                    25.2                            44.6      0.341
73                    24.9                            45.3      0.396
74                    25.2                            47.0      0.413
75                    27.7                            44.3      0.351
76                    27.2                            46.6      0.440
77                    29.5                            44.0      0.380
78                    28.1                            47.0      0.416
79                    28.8                            45.8      0.347
80                    29.2                            45.5      0.408
81                    28.7                            46.3      0.356
82                    29.7                            47.7      0.472
83                    35.0                            46.8      0.429
84                    37.7                            46.6      0.591
85                    37.3                            47.3      0.414
86                    38.3                            47.8      0.459
87                    40.9                            46.3      0.530
88                    38.2                            49.6      0.480
89                    41.0                            46.8      0.386
90                    43.6                            45.7      0.507
91                    43.1                            48.5      0.481
92                    45.8                            49.4      0.621
93                    48.6                            47.0      0.486
94                    46.4                            49.5      0.637
95                    56.3                            48.2      0.551
96                    53.9                            51.2      0.669
97                    58.2                            49.7      0.519
98                    60.5                            48.0      0.481
99                    55.9                            52.4      0.651
100                   64.8                            54.1      0.609
101                   82.5                            55.7      0.591

     Headcount Ratio Rural  Intensity of Deprivation Rural     first name
0                     0.09                            33.3     Kazakhstan
1                     0.50                            40.3         Serbia
2                     0.70                            37.1     Kyrgyzstan
3                     3.18                            38.7        Tunisia
4                     0.39                            36.9        Armenia
5                     1.17                            35.5     Macedonia,
6                     0.32                            34.3   Turkmenistan
7                     1.01                            34.7       Moldova,
8                     4.25                            40.4         Guyana
9                     0.09                            41.1     Montenegro
10                    1.05                            35.2          Saint
11                    3.37                            41.1         Mexico
12                    1.07                            36.5       Thailand
13                    0.44                            38.0         Bosnia
14                    2.70                            40.0        Algeria
15                    1.87                            37.7        Albania
16                    1.77                            36.3        Ukraine
17                    0.57                            34.3       Barbados
18                    2.86                            36.6     Uzbekistan
19                    0.88                            36.2      Palestine
20                    2.49                            38.7        Jamaica
21                    7.68                            39.3        Ecuador
22                    6.76                            35.8       Maldives
23                    1.81                            36.2         Jordan
24                    6.98                            39.9         Belize
25                    6.74                            42.1          China
26                    4.39                            38.5          Egypt
27                   14.85                            42.3       Suriname
28                   14.44                            42.6       Colombia
29                   31.21                            44.4        Morocco
..                     ...                             ...            ...
72                   65.90                            51.7          Haiti
73                   73.70                            53.8     Madagascar
74                   72.92                            56.6     Mauritania
75                   68.56                            51.2      Tanzania,
76                   83.18                            52.9       Djibouti
77                   74.20                            51.3         Zambia
78                   69.98                            59.5        Nigeria
79                   64.66                            53.6    Afghanistan
80                   77.07                            52.9         Uganda
81                   64.50                            55.1          Sudan
82                   81.04                            58.3        Senegal
83                   78.04                            55.0           CÃ´te
84                   92.61                            63.9         Guinea
85                   77.03                            53.7    Timor-Leste
86                   81.97                            56.0         Gambia
87                   87.73                            60.5           Mali
88                   83.90                            57.2     Mozambique
89                   76.90                            50.2          Benin
90                   85.36                            59.4  Guinea-Bissau
91                   84.91                            56.6        Burundi
92                   94.66                            65.6        Burkina
93                   88.18                            55.1         Congo,
94                   96.27                            66.2       Ethiopia
95                   92.03                            59.8         Sierra
96                   96.19                            69.5          Niger
97                   89.79                            57.8        Central
98                   84.86                            56.6        Liberia
99                   96.92                            67.2        Somalia
100                  93.41                            65.2           Chad
101                  94.00                            62.8          South

[102 rows x 9 columns]

UnicodeEncodeError: 'ascii' codec can't encode character u'\xf4' in position 1: ordinal not in range(128)

In [11]:
#4.	Create a Table where Intensity of Rural Deprivation is less than the average(Data1)
print "Avg Intensity of Rural Deprivation", np.mean(data1["Intensity of Deprivation Rural"])
IRD_table =data1[(data1["Intensity of Deprivation Rural"] < np.mean(data1["Intensity of Deprivation Rural"]))] 
print IRD_table
#IRD_table.to_csv("C:\\Users\\SAGEABLE\\Desktop\\case study\\4table.csv")  # to output in csv file

Avg Intensity of Rural Deprivation 46.8245098039
    ISO                                     Country  MPI Urban  \
0   KAZ                                  Kazakhstan      0.000
1   SRB                                      Serbia        NaN
2   KGZ                                  Kyrgyzstan        NaN
3   TUN                                     Tunisia        NaN
4   ARM                                     Armenia      0.001
5   MKD  Macedonia, The former Yugoslav Republic of      0.001
6   TKM                                Turkmenistan      0.001
7   MDA                        Moldova, Republic of      0.001
8   GUY                                      Guyana      0.001
9   MNE                                  Montenegro      0.002
10  LCA                                 Saint Lucia      0.002
11  MEX                                      Mexico      0.002
12  THA                                    Thailand      0.002
13  BIH                      Bosnia and Herzegovina      0.002
14  DZA                                     Algeria      0.003
15  ALB                                     Albania      0.003
16  UKR                                     Ukraine      0.003
17  BRB                                    Barbados      0.004
18  UZB                                  Uzbekistan      0.004
19  PSE                        Palestine, State ofa      0.004
20  JAM                                     Jamaica      0.004
21  ECU                                     Ecuador      0.005
22  MDV                                    Maldives      0.005
23  JOR                                      Jordan      0.006
24  BLZ                                      Belize      0.006
25  CHN                                       China      0.007
26  EGY                                       Egypt      0.008
27  SUR                                    Suriname      0.008
28  COL                                    Colombia      0.009
29  MAR                                     Morocco      0.009
30  AZE                                  Azerbaijan      0.009
31  SLV                                 El Salvador      0.010
32  MNG                                    Mongolia      0.010
33  SYR                        Syrian Arab Republic      0.011
34  PER                                        Peru      0.011
35  VNM                                    Viet Nam      0.013
36  ZAF                                South Africa      0.014
37  NIC                                   Nicaragua      0.015
38  BRA                                      Brazil      0.016
39  TTO                         Trinidad and Tobago      0.018
40  BTN                                      Bhutan      0.019
41  BOL             Bolivia, Plurinational State of      0.019
42  TJK                                  Tajikistan      0.020
43  SWZ                                   Swaziland      0.020
44  HND                                    Honduras      0.022
45  IRQ                                        Iraq      0.028
46  KHM                                    Cambodia      0.028
47  DOM                          Dominican Republic      0.029
48  NPL                                       Nepal      0.031
50  ZWE                                    Zimbabwe      0.034
52  VUT                                     Vanuatu      0.039
53  IDN                                   Indonesia      0.039
54  MMR                                     Myanmar      0.040
55  LSO                                     Lesotho      0.044
56  GAB                                       Gabon      0.044
57  GTM                                   Guatemala      0.048
58  IND                                       India      0.064
59  STP                       Sao Tome and Principe      0.067

    Headcount Ratio Urban  Intensity of Deprivation Urban  MPI Rural  \
0                     0.0                            33.3      0.000
1                     0.1                            41.4      0.002
2                     0.1                            40.2      0.003
3                     0.1                            35.6      0.012
4                     0.2                            33.3      0.001
5                     0.3                            36.3      0.004
6                     0.4                            33.9      0.001
7                     0.3                            42.2      0.003
8                     0.4                            38.2      0.017
9                     0.4                            47.2      0.000
10                    0.5                            36.7      0.004
11                    0.5                            38.0      0.014
12                    0.6                            37.1      0.004
13                    0.6                             NaN      0.002
14                    0.7                            36.9      0.011
15                    0.8                            37.7      0.007
16                    1.0                            33.7      0.006
17                    1.1                            34.2      0.002
18                    1.1                            33.9      0.010
19                    1.1                            38.5      0.003
20                    1.1                            40.0      0.010
21                    1.5                            36.5      0.030
22                    1.6                            33.3      0.024
23                    1.7                            34.7      0.007
24                    1.6                            37.9      0.028
25                    1.9                            38.9      0.028
26                    2.1                            36.8      0.017
27                    2.3                            36.7      0.063
28                    2.3                            37.2      0.061
29                    2.4                            36.2      0.139
30                    2.5                            37.1      0.035
31                    2.4                            40.3      0.052
32                    2.8                            36.4      0.093
33                    3.0                            35.5      0.023
34                    2.9                            38.6      0.113
35                    3.6                            36.9      0.036
36                    3.6                            37.4      0.068
37                    3.8                            40.0      0.150
38                    4.1                            38.3      0.054
39                    5.4                            33.6        NaN
40                    4.7                            39.5      0.159
41                    4.9                            39.4      0.191
42                    5.5                            36.3      0.065
43                    5.2                            39.4      0.083
44                    5.2                            41.6      0.119
45                    7.7                            36.0      0.083
46                    7.1                            39.4      0.169
47                    7.9                            37.2      0.048
48                    7.0                            43.8      0.147
50                    8.7                            39.3      0.202
52                    9.8                            39.3      0.155
53                   10.2                            38.7      0.093
54                    9.6                            41.7      0.168
55                   11.0                            39.8      0.179
56                   10.9                            40.7      0.209
57                   10.7                            44.5      0.161
58                   14.8                            43.3      0.250
59                   15.9                            42.3      0.110

    Headcount Ratio Rural  Intensity of Deprivation Rural    first name
0                    0.09                            33.3    Kazakhstan
1                    0.50                            40.3        Serbia
2                    0.70                            37.1    Kyrgyzstan
3                    3.18                            38.7       Tunisia
4                    0.39                            36.9       Armenia
5                    1.17                            35.5    Macedonia,
6                    0.32                            34.3  Turkmenistan
7                    1.01                            34.7      Moldova,
8                    4.25                            40.4        Guyana
9                    0.09                            41.1    Montenegro
10                   1.05                            35.2         Saint
11                   3.37                            41.1        Mexico
12                   1.07                            36.5      Thailand
13                   0.44                            38.0        Bosnia
14                   2.70                            40.0       Algeria
15                   1.87                            37.7       Albania
16                   1.77                            36.3       Ukraine
17                   0.57                            34.3      Barbados
18                   2.86                            36.6    Uzbekistan
19                   0.88                            36.2     Palestine
20                   2.49                            38.7       Jamaica
21                   7.68                            39.3       Ecuador
22                   6.76                            35.8      Maldives
23                   1.81                            36.2        Jordan
24                   6.98                            39.9        Belize
25                   6.74                            42.1         China
26                   4.39                            38.5         Egypt
27                  14.85                            42.3      Suriname
28                  14.44                            42.6      Colombia
29                  31.21                            44.4       Morocco
30                   8.80                            40.2    Azerbaijan
31                  12.51                            41.8            El
32                  22.24                            42.0      Mongolia
33                   6.02                            38.5        Syrian
34                  27.13                            41.6          Peru
35                   8.79                            41.4          Viet
36                  17.17                            39.7         South
37                  32.81                            45.8     Nicaragua
38                  11.96                            45.1        Brazil
39                   5.66                            35.4      Trinidad
40                  35.98                            44.2        Bhutan
41                  42.98                            44.4      Bolivia,
42                  15.63                            41.3    Tajikistan
43                  19.84                            41.7     Swaziland
44                  25.67                            46.5      Honduras
45                  20.48                            40.6          Iraq
46                  38.06                            44.5      Cambodia
47                  11.69                            41.0     Dominican
48                  33.13                            44.2         Nepal
50                  46.27                            43.7      Zimbabwe
52                  36.13                            43.0       Vanuatu
53                  20.69                            45.0     Indonesia
54                  37.46                            44.8       Myanmar
55                  40.43                            44.3       Lesotho
56                  46.55                            44.8         Gabon
57                  35.05                            45.9     Guatemala
58                  53.49                            46.7         India
59                  26.18                            42.1           Sao

In [6]:
#5.	Analyze the Data from both the Datasets and Try to Get the Country level Data map to its Sub-national region data.
country_level=data2.groupby(['ISO country code','Country','World region'])["MPI National","MPI Regional","Headcount Ratio Regional","Intensity of deprivation Regional"].mean()
#country_level.to_csv("C:\\Users\\SAGEABLE\\Desktop\\case study\\5table.csv")  # to output in csv file

In [13]:
#6.	Identify the Data which is present in Data 1 but Missing in Data2
data=data1.copy(deep= True) 
unique_countries= np.array(sorted(set(data2.Country)))
a=[i for i in range(len(data.Country)) if data.Country[i] in unique_countries]
data.drop(data.index[a],inplace= True)
print 'Following countries Data missing in data2'
print data
#data.to_csv("C:\\Users\\SAGEABLE\\Desktop\\case study\\6table.csv")  # to output in csv file

Following countries Data missing in data2
    ISO                                     Country  MPI Urban  \
0   KAZ                                  Kazakhstan      0.000
1   SRB                                      Serbia        NaN
2   KGZ                                  Kyrgyzstan        NaN
3   TUN                                     Tunisia        NaN
4   ARM                                     Armenia      0.001
5   MKD  Macedonia, The former Yugoslav Republic of      0.001
6   TKM                                Turkmenistan      0.001
7   MDA                        Moldova, Republic of      0.001
9   MNE                                  Montenegro      0.002
10  LCA                                 Saint Lucia      0.002
11  MEX                                      Mexico      0.002
12  THA                                    Thailand      0.002
13  BIH                      Bosnia and Herzegovina      0.002
14  DZA                                     Algeria      0.003
15  ALB                                     Albania      0.003
16  UKR                                     Ukraine      0.003
17  BRB                                    Barbados      0.004
19  PSE                        Palestine, State ofa      0.004
22  MDV                                    Maldives      0.005
30  AZE                                  Azerbaijan      0.009
36  ZAF                                South Africa      0.014
52  VUT                                     Vanuatu      0.039
58  IND                                       India      0.064
99  SOM                                     Somalia      0.293

    Headcount Ratio Urban  Intensity of Deprivation Urban  MPI Rural  \
0                     0.0                            33.3      0.000
1                     0.1                            41.4      0.002
2                     0.1                            40.2      0.003
3                     0.1                            35.6      0.012
4                     0.2                            33.3      0.001
5                     0.3                            36.3      0.004
6                     0.4                            33.9      0.001
7                     0.3                            42.2      0.003
9                     0.4                            47.2      0.000
10                    0.5                            36.7      0.004
11                    0.5                            38.0      0.014
12                    0.6                            37.1      0.004
13                    0.6                             NaN      0.002
14                    0.7                            36.9      0.011
15                    0.8                            37.7      0.007
16                    1.0                            33.7      0.006
17                    1.1                            34.2      0.002
19                    1.1                            38.5      0.003
22                    1.6                            33.3      0.024
30                    2.5                            37.1      0.035
36                    3.6                            37.4      0.068
52                    9.8                            39.3      0.155
58                   14.8                            43.3      0.250
99                   55.9                            52.4      0.651

    Headcount Ratio Rural  Intensity of Deprivation Rural    first name
0                    0.09                            33.3    Kazakhstan
1                    0.50                            40.3        Serbia
2                    0.70                            37.1    Kyrgyzstan
3                    3.18                            38.7       Tunisia
4                    0.39                            36.9       Armenia
5                    1.17                            35.5    Macedonia,
6                    0.32                            34.3  Turkmenistan
7                    1.01                            34.7      Moldova,
9                    0.09                            41.1    Montenegro
10                   1.05                            35.2         Saint
11                   3.37                            41.1        Mexico
12                   1.07                            36.5      Thailand
13                   0.44                            38.0        Bosnia
14                   2.70                            40.0       Algeria
15                   1.87                            37.7       Albania
16                   1.77                            36.3       Ukraine
17                   0.57                            34.3      Barbados
19                   0.88                            36.2     Palestine
22                   6.76                            35.8      Maldives
30                   8.80                            40.2    Azerbaijan
36                  17.17                            39.7         South
52                  36.13                            43.0       Vanuatu
58                  53.49                            46.7         India
99                  96.92                            67.2       Somalia

In [45]:
#7.	Get the average of Intensity of deprivation Regional from Dat2 for Country-Wise and World Region Wise-Accordingly.
country_wise=data2.groupby(['Country'])['Intensity of deprivation Regional'].mean()
print 'country wise data'
print country_wise
world_wide=data2.groupby(['World region'])['Intensity of deprivation Regional'].mean()
print 'World region wise data'
print world_wide
country_wise.to_csv("C:\\Users\\SAGEABLE\\Desktop\\case study\\7-1table.csv")  # to output in csv file

country wise data
Country
Afghanistan                          51.908824
Bangladesh                           47.214286
Belize                               39.028571
Benin                                48.550000
Bhutan                               42.673684
Bolivia, Plurinational State of      43.100000
Brazil                               41.170370
Burkina Faso                         62.930769
Burundi                              54.100000
Cambodia                             44.278947
Cameroon                             46.616667
Central African Republic             55.062500
Chad                                 64.090476
China                                41.000000
Colombia                             39.137500
Comoros                              47.033333
Congo, Democratic Republic of the    52.754545
Congo, Republic of                   46.816667
Cote d'Ivoire                        53.172727
Djibouti                             47.750000
Dominican Republic                   39.230000
Ecuador                              38.425000
Egypt                                37.240000
El Salvador                          41.171429
Ethiopia                             62.218182
Gabon                                43.050000
Gambia                               52.800000
Ghana                                45.480000
Guatemala                            44.943478
Guinea                               59.975000
                                       ...
Mozambique                           52.809091
Myanmar                              44.253333
Namibia                              44.800000
Nepal                                43.200000
Nicaragua                            43.152941
Niger                                63.750000
Nigeria                              50.256757
Pakistan                             50.766667
Peru                                 40.162500
Philippines                          47.547059
Rwanda                               47.440000
Sao Tome and Principe                42.125000
Senegal                              55.450000
Sierra Leone                         56.907143
South Sudan                          60.322222
Sudan                                52.961111
Suriname                             37.820000
Swaziland                            41.500000
Syrian Arab Republic                 36.535714
Tajikistan                           39.320000
Tanzania, United Republic of         48.788889
Timor-Leste                          52.300000
Togo                                 48.916667
Trinidad and Tobago                  35.200000
Uganda                               52.580000
Uzbekistan                           35.216667
Viet Nam                             40.233333
Yemen                                48.938095
Zambia                               49.560000
Zimbabwe                             42.480000
Name: Intensity of deprivation Regional, Length: 78, dtype: float64
World region wise data
World region
Arab States                    42.653913
East Asia and the Pacific      45.601562
Europe and Central Asia        37.081818
Latin America and Caribbean    41.538710
South Asia                     47.639506
Sub-Saharan Africa             51.870302
Name: Intensity of deprivation Regional, dtype: float64